services:
  - type: web
    name: stock-market-prediction
    env: python
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --worker-class sync --timeout 60 --graceful-timeout 45 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
